config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :votes
  resources :questions
  resources :projects
  resources :districts
  get 'users/index'
  root 'users#index'


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks' 

  }

  
    




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/district.rb
class District < ApplicationRecord
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  load_and_authorize_resource

  # GET /districts
  # GET /districts.json
  def index
    if params[:q].present?
      @districts = District.where('name like ?', "%#{params[:q]}%")
    else
      @districts = District.all
    end
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'Distrito creado correctamente.' }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1
  # PATCH/PUT /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to @district, notice: 'Distrito actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district.destroy
    respond_to do |format|
      format.html { redirect_to districts_url, notice: 'Distrito eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_params
      params.require(:district).permit(:name, :distrito)
    end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_district.html.erb
<tr>

  <td><%= district.name %></td>
  <td><%= district.distrito%></td>
  <td><%= link_to 'Ver', district_path(district), class: 'btn btn-primary text-white' %></td>
  <td><%= link_to 'Editar', edit_district_path(district), class: 'btn btn-success text-white' %></td>
  <td><%= link_to 'Eliminar',district, class: 'btn btn-danger text-white',  method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/districts/_form.html.erb
<%= form_with(model: district, local: true) do |form| %>
  <% if district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
      <% district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Distrito%>
    <%= form.number_field :distrito %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing District</h1>

<%= render 'form', district: @district %>

<%= link_to 'Ver', @district %> |
<%= link_to 'Atrás', districts_path %>

app/views/districts/index.html.erb
<div class="container-fluid table-responsive" id="districts">
  <h1>Comunas</h1>

<form action="<%= districts_path%>">
  <h3>Buscador <input name="q"></h3>
  </form>
<hr>

  <table class="table table-bordered">
    <thead class=thead-dark>

      <tr>
        <th>Nombre</th>
        <th>Distrito</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>

      <%= render @districts %>

    
    </tbody>
  </table>

  <br>

  <%= link_to 'Agregar distrito', new_district_path %>

  <script>
    $("[name=q]").keyup(function(event){
      $.ajax({
        url: '<%= districts_path%>',
        type: 'GET',
        dataType: 'script',
        data: {q: $(this).val()}
      })
    });

  </script>
</div>

app/views/districts/index.js.erb
$("#districts").html("<%= j render @districts %>");

app/views/districts/new.html.erb
<h1>Nuevo Distrito</h1>

<%= render 'form', district: @district %>

<%= link_to 'Volver', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @district.name %>
</p>
<p>
  <strong>Distrito:</strong>
  <%= @district.distrito %>
</p>

<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>