config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :votes
  resources :questions
  resources :projects
  resources :districts
  get 'users/index'
  root 'users#index'


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks' 

  }

  
    




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
    <nav class="navbar navbar navbar-expand-lg  navbar-dark " id="footer">
    <h1>cas</h1>
    
  </nav>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar navbar-expand-lg  navbar-dark " id="navbarcolor">
    <a id="logo" class="navbar-brand active" href="<%= root_path  %>" ><i class="fas fa-vote-yea"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <ul class="navbar-nav">

          <% if current_user.admin? %>

            <li class="nav-item dropdown text-white">
                <a class="nav-link dropdown-toggle" href="<%=  %>" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Panel de control
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="<%= new_admin_user_session_path %>">Administrar</a>

                  <a class="dropdown-item" href="<%= districts_path  %>">Distritos</a>
                  <a class="dropdown-item" href="<%=projects_path  %>">Proyectos</a>
                  <a class="dropdown-item" href="<%= votes_path %>">Votos</a>
                  <a class="dropdown-item" href="<%= questions_path %>">Crear votación</a>
                </div>
            </li>
            <li class="nav-item">
              <%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link') %>
            </li>


				  <% end %>


          <% if current_user.voter? %>

            <li class="nav-item active">
              <a class="nav-link" href="<%= votes_path  %>">Votar</a>
            </li>       

         

            <li class="nav-item">
              <%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link') %>
            </li>
          <% end %>

          <% if current_user.parliamentary? %>

            <li class="nav-item active">
              <a class="nav-link"  href="<%= votes_path %>">Votar</a>
            </li>
         

         

            <li class="nav-item">
              <%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link') %>
            </li>
          <% end %>

          <% else %>
            <li class="nav-item active">
              <a class="nav-link" href="<%= new_user_session_path %>">Iniciar sesión</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<%= new_user_registration_path %>">Registrarse</a>
            </li>
          <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title>Proyectofinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, user-scalable=no">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/876416a4e6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
      
    <% if alert.present? %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    
    <%= yield %>
  
  </body>
</html>